sudo: required
services:
  - docker

before_install:
  - docker build -t oliniusz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true oliniusz/docker-react npm run test




  # access_key_id: $AWS_ACCESS_KEY
  # secret_access_key: $AWS_SECRET_KEY